In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('datos_delitos.csv')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 1: invalid continuation byte

In [3]:
df = pd.read_csv('datos_delitos.csv', encoding='ISO-8859-1')
df.head()

,Año,Clave_Ent,Entidad,Bien jurídico afectado,Tipo de delito,Subtipo de delito,Modalidad,Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre
0,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma de fuego,3,0,2,1,1,1,2,1,2,2,2,1
1,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma blanca,1,1,0,0,0,1,0,1,0,0,0,1
2,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con otro elemento,0,0,2,2,3,2,0,1,2,0,0,0
3,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,No especificado,2,0,0,1,0,0,0,0,0,0,0,0
4,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio culposo,Con arma de fuego,0,0,0,0,1,0,0,0,0,0,0,0

In [4]:
df.tail(3)

,Año,Clave_Ent,Entidad,Bien jurídico afectado,Tipo de delito,Subtipo de delito,Modalidad,Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre
34493,2025,32,Zacatecas,Otros bienes jurídicos afectados (del fuero co...,Delitos cometidos por servidores públicos,Delitos cometidos por servidores públicos,Delitos cometidos por servidores públicos,37,35,24,40,30,32,34,25,20,31,31,31
34494,2025,32,Zacatecas,Otros bienes jurídicos afectados (del fuero co...,Electorales,Electorales,Electorales,8,3,1,0,2,2,0,0,1,0,2,0
34495,2025,32,Zacatecas,Otros bienes jurídicos afectados (del fuero co...,Otros delitos del Fuero Común,Otros delitos del Fuero Común,Otros delitos del Fuero Común,190,164,184,172,98,103,108,111,134,97,92,80

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 34496 entries, 0 to 34495
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Año                     34496 non-null  int64
 1   Clave_Ent               34496 non-null  int64
 2   Entidad                 34496 non-null  str
 3   Bien jurídico afectado  34496 non-null  str
 4   Tipo de delito          34496 non-null  str
 5   Subtipo de delito       34496 non-null  str
 6   Modalidad               34496 non-null  str
 7   Enero                   34496 non-null  int64
 8   Febrero                 34496 non-null  int64
 9   Marzo                   34496 non-null  int64
 10  Abril                   34496 non-null  int64
 11  Mayo                    34496 non-null  int64
 12  Junio                   34496 non-null  int64
 13  Julio                   34496 non-null  int64
 14  Agosto                  34496 non-null  int64
 15  Septiembre              34496 non-null  int64
 16  Octubre                 34496 non-null  int64
 17  Noviembre               34496 non-null  int64
 18  Diciembre               34496 non-null  int64
dtypes: int64(14), str(5)
memory usage: 5.0 MB

In [6]:
for col in df.columns:
    print(col)

Año
Clave_Ent
Entidad
Bien jurídico afectado
Tipo de delito
Subtipo de delito
Modalidad
Enero
Febrero
Marzo
Abril
Mayo
Junio
Julio
Agosto
Septiembre
Octubre
Noviembre
Diciembre

In [7]:
def limpiar_columnas(df):
    columnas_limpias = []
    for col in df.columns:
        # convertir a minusculas, reemplazar espacios por guiones bajos y eliminar caracteres especiales
        col = col.lower().replace(" ", "_").replace("ñ", "ni").replace(".", "").replace("á", "a").replace("é", "e").replace("í","i").replace("ó", "o").replace("ú", "u")
        columnas_limpias.append(col)
    
    df.columns = columnas_limpias
    
    return df

In [8]:
df.head(2)

,Año,Clave_Ent,Entidad,Bien jurídico afectado,Tipo de delito,Subtipo de delito,Modalidad,Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre
0,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma de fuego,3,0,2,1,1,1,2,1,2,2,2,1
1,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma blanca,1,1,0,0,0,1,0,1,0,0,0,1

In [9]:
df = limpiar_columnas(df)

In [10]:
df.head(3)

,anio,clave_ent,entidad,bien_juridico_afectado,tipo_de_delito,subtipo_de_delito,modalidad,enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre
0,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma de fuego,3,0,2,1,1,1,2,1,2,2,2,1
1,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma blanca,1,1,0,0,0,1,0,1,0,0,0,1
2,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con otro elemento,0,0,2,2,3,2,0,1,2,0,0,0

In [11]:
df[['anio', 'entidad']]

       anio         entidad
0      2015  Aguascalientes
1      2015  Aguascalientes
2      2015  Aguascalientes
3      2015  Aguascalientes
4      2015  Aguascalientes
...     ...             ...
34491  2025       Zacatecas
34492  2025       Zacatecas
34493  2025       Zacatecas
34494  2025       Zacatecas
34495  2025       Zacatecas

[34496 rows x 2 columns]

In [12]:
df = df[['anio', 'clave_ent', 'entidad', 'tipo_de_delito', 'subtipo_de_delito', 'modalidad','enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio', 'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre']]
df.head(2)

,anio,clave_ent,entidad,tipo_de_delito,subtipo_de_delito,modalidad,enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre
0,2015,1,Aguascalientes,Homicidio,Homicidio doloso,Con arma de fuego,3,0,2,1,1,1,2,1,2,2,2,1
1,2015,1,Aguascalientes,Homicidio,Homicidio doloso,Con arma blanca,1,1,0,0,0,1,0,1,0,0,0,1

In [13]:
print("Shape: ", df.shape)

Shape:  (34496, 18)

In [14]:
datos_long = df.melt(id_vars=['anio', 'clave_ent', 'entidad','tipo_de_delito', 'subtipo_de_delito', 'modalidad'], var_name='nombre_mes', value_name='frecuencia')

In [15]:
print("Shape: ", datos_long.shape)

Shape:  (413952, 8)

In [16]:
datos_long.head(5)

,anio,clave_ent,entidad,tipo_de_delito,subtipo_de_delito,modalidad,nombre_mes,frecuencia
0,2015,1,Aguascalientes,Homicidio,Homicidio doloso,Con arma de fuego,enero,3
1,2015,1,Aguascalientes,Homicidio,Homicidio doloso,Con arma blanca,enero,1
2,2015,1,Aguascalientes,Homicidio,Homicidio doloso,Con otro elemento,enero,0
3,2015,1,Aguascalientes,Homicidio,Homicidio doloso,No especificado,enero,2
4,2015,1,Aguascalientes,Homicidio,Homicidio culposo,Con arma de fuego,enero,0

In [17]:
datos_long.info()

<class 'pandas.DataFrame'>
RangeIndex: 413952 entries, 0 to 413951
Data columns (total 8 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   anio               413952 non-null  int64
 1   clave_ent          413952 non-null  int64
 2   entidad            413952 non-null  str
 3   tipo_de_delito     413952 non-null  str
 4   subtipo_de_delito  413952 non-null  str
 5   modalidad          413952 non-null  str
 6   nombre_mes         413952 non-null  str
 7   frecuencia         413952 non-null  int64
dtypes: int64(3), str(5)
memory usage: 25.3 MB

In [18]:
#En esta entrada estoy agregando el subtipo de delito, ya que en el ejercicio donde usaremos la base de datos resultante, necesitaremos ese dato:
datos_long = datos_long.groupby(['anio', 'clave_ent', 'entidad', 'tipo_de_delito', 'subtipo_de_delito', 'nombre_mes'])['frecuencia'].sum().reset_index()

In [19]:
#Cambiando el filtro para verificar que tengo información suficiente:
datos_long[datos_long.subtipo_de_delito == 'Homicidio doloso'].sample(15)

,anio,clave_ent,entidad,tipo_de_delito,subtipo_de_delito,nombre_mes,frecuencia
231235,2025,31,Yucatán,Homicidio,Homicidio doloso,marzo,2
81412,2018,28,Tamaulipas,Homicidio,Homicidio doloso,febrero,69
143455,2021,26,Sonora,Homicidio,Homicidio doloso,marzo,142
66894,2018,6,Colima,Homicidio,Homicidio doloso,junio,52
151369,2022,6,Colima,Homicidio,Homicidio doloso,agosto,63
179091,2023,16,Michoacán de Ocampo,Homicidio,Homicidio doloso,enero,124
229918,2025,29,Tlaxcala,Homicidio,Homicidio doloso,octubre,7
199557,2024,15,México,Homicidio,Homicidio doloso,noviembre,130
178431,2023,15,México,Homicidio,Homicidio doloso,enero,216
161271,2022,21,Puebla,Homicidio,Homicidio doloso,enero,60
82731,2018,30,Veracruz de Ignacio de la Llave,Homicidio,Homicidio doloso,enero,131
200219,2024,16,Michoacán de Ocampo,Homicidio,Homicidio doloso,septiembre,87
102531,2019,28,Tamaulipas,Homicidio,Homicidio doloso,enero,53
156652,2022,14,Jalisco,Homicidio,Homicidio doloso,febrero,119
155993,2022,13,Hidalgo,Homicidio,Homicidio doloso,julio,25

In [20]:
datos_long[['clave_ent', 'entidad']].drop_duplicates().sort_values('entidad')

       clave_ent                          entidad
0              1                   Aguascalientes
660            2                  Baja California
1320           3              Baja California Sur
1980           4                         Campeche
3960           7                          Chiapas
4620           8                        Chihuahua
5280           9                 Ciudad de México
2640           5             Coahuila de Zaragoza
3300           6                           Colima
5940          10                          Durango
6600          11                       Guanajuato
7260          12                         Guerrero
7920          13                          Hidalgo
8580          14                          Jalisco
9900          16              Michoacán de Ocampo
10560         17                          Morelos
9240          15                           México
11220         18                          Nayarit
11880         19                       Nuevo León
12540         20                           Oaxaca
13200         21                           Puebla
13860         22                        Querétaro
14520         23                     Quintana Roo
15180         24                  San Luis Potosí
15840         25                          Sinaloa
16500         26                           Sonora
17160         27                          Tabasco
17820         28                       Tamaulipas
18480         29                         Tlaxcala
19140         30  Veracruz de Ignacio de la Llave
19800         31                          Yucatán
20460         32                        Zacatecas

In [21]:
datos_long[datos_long['clave_ent'] == 19].sample(15)

,anio,clave_ent,entidad,tipo_de_delito,subtipo_de_delito,nombre_mes,frecuencia
180938,2023,19,Nuevo León,Daño a la propiedad,Daño a la propiedad,diciembre,506
75646,2018,19,Nuevo León,Rapto,Rapto,octubre,10
96725,2019,19,Nuevo León,Otros delitos que atentan contra la libertad p...,Otros delitos que atentan contra la libertad p...,julio,181
33293,2016,19,Nuevo León,Lesiones,Lesiones dolosas,julio,597
139138,2021,19,Nuevo León,Robo,Robo de vehículo automotor,octubre,316
160033,2022,19,Nuevo León,Otros delitos contra el patrimonio,Otros delitos contra el patrimonio,agosto,4
181097,2023,19,Nuevo León,Incesto,Incesto,julio,0
96683,2019,19,Nuevo León,Otros delitos contra el patrimonio,Otros delitos contra el patrimonio,septiembre,9
202536,2024,19,Nuevo León,Secuestro,Secuestro,abril,3
12245,2015,19,Nuevo León,Otros delitos que atentan contra la libertad p...,Otros delitos que atentan contra la libertad p...,julio,206
202174,2024,19,Nuevo León,Fraude,Fraude,octubre,466
75587,2018,19,Nuevo León,Otros delitos contra la sociedad,Otros delitos contra la sociedad,septiembre,0
138650,2021,19,Nuevo León,Allanamiento de morada,Allanamiento de morada,diciembre,50
54667,2017,19,Nuevo León,Robo,Robo en transporte individual,marzo,2
138623,2021,19,Nuevo León,Abuso de confianza,Abuso de confianza,septiembre,77

In [22]:
datos_long[(datos_long['clave_ent'] == 19) & (datos_long['tipo_de_delito'] == 'Homicidio')]

,anio,clave_ent,entidad,tipo_de_delito,subtipo_de_delito,nombre_mes,frecuencia
12096,2015,19,Nuevo León,Homicidio,Homicidio culposo,abril,45
12097,2015,19,Nuevo León,Homicidio,Homicidio culposo,agosto,46
12098,2015,19,Nuevo León,Homicidio,Homicidio culposo,diciembre,65
12099,2015,19,Nuevo León,Homicidio,Homicidio culposo,enero,32
12100,2015,19,Nuevo León,Homicidio,Homicidio culposo,febrero,36
...,...,...,...,...,...,...,...
223315,2025,19,Nuevo León,Homicidio,Homicidio doloso,marzo,81
223316,2025,19,Nuevo León,Homicidio,Homicidio doloso,mayo,59
223317,2025,19,Nuevo León,Homicidio,Homicidio doloso,noviembre,50
223318,2025,19,Nuevo León,Homicidio,Homicidio doloso,octubre,39
223319,2025,19,Nuevo León,Homicidio,Homicidio doloso,septiembre,58

In [23]:
datos_long[
    (datos_long['clave_ent'] == 20) &
    (datos_long['tipo_de_delito'] == 'Homicidio') &
    (datos_long['anio'] == 2024) &
    (datos_long['nombre_mes'] == 'enero') 
]

,anio,clave_ent,entidad,tipo_de_delito,subtipo_de_delito,nombre_mes,frecuencia
202839,2024,20,Oaxaca,Homicidio,Homicidio culposo,enero,87
202851,2024,20,Oaxaca,Homicidio,Homicidio doloso,enero,67

In [24]:
datos_long.sample(2)

,anio,clave_ent,entidad,tipo_de_delito,subtipo_de_delito,nombre_mes,frecuencia
142180,2021,24,San Luis Potosí,Lesiones,Lesiones culposas,febrero,40
56779,2017,23,Quintana Roo,Abuso de confianza,Abuso de confianza,marzo,46

In [25]:
datos_long["nueva_columna"] = "dato vacío"
datos_long.sample(6)

,anio,clave_ent,entidad,tipo_de_delito,subtipo_de_delito,nombre_mes,frecuencia,nueva_columna
142824,2021,25,Sinaloa,Incumplimiento de obligaciones de asistencia f...,Incumplimiento de obligaciones de asistencia f...,abril,18,dato vacío
204826,2024,23,Quintana Roo,Homicidio,Homicidio culposo,octubre,75,dato vacío
56327,2017,22,Querétaro,Homicidio,Homicidio culposo,septiembre,27,dato vacío
7174,2015,11,Guanajuato,Robo,Robo en transporte público individual,octubre,0,dato vacío
60910,2017,29,Tlaxcala,Falsificación,Falsificación,octubre,0,dato vacío
10615,2015,17,Morelos,Allanamiento de morada,Allanamiento de morada,marzo,45,dato vacío

In [26]:
# Diccionario de ayuda para convertir
meses = {
    "enero": 1,
    "febrero": 2,
    "marzo": 3,
    "abril": 4,
    "mayo": 5,
    "junio": 6,
    "julio": 7,
    "agosto": 8,
    "septiembre": 9,
    "octubre": 10,
    "noviembre": 11,
    "diciembre": 12
}

datos_long['mes'] = datos_long['nombre_mes'].map(meses)
datos_long.sample(5)

,anio,clave_ent,entidad,tipo_de_delito,subtipo_de_delito,nombre_mes,frecuencia,nueva_columna,mes
183940,2023,23,Quintana Roo,Robo,Robo a transeúnte en espacio abierto al público,febrero,40,dato vacío,2
19864,2015,31,Yucatán,Amenazas,Amenazas,febrero,364,dato vacío,2
86152,2019,3,Baja California Sur,Otros delitos del Fuero Común,Otros delitos del Fuero Común,febrero,103,dato vacío,2
148166,2022,1,Aguascalientes,Otros delitos contra la familia,Otros delitos contra la familia,diciembre,0,dato vacío,12
42665,2017,1,Aguascalientes,Robo,Robo a casa habitación,julio,278,dato vacío,7

In [28]:
datos_long["anio_mes"] = datos_long["anio"].astype(str) + datos_long["mes"].astype(str)
datos_long.sample(6)

,anio,clave_ent,entidad,tipo_de_delito,subtipo_de_delito,nombre_mes,frecuencia,nueva_columna,mes,anio_mes
211130,2024,32,Zacatecas,Trata de personas,Trata de personas,diciembre,3,dato vacío,12,202412
199057,2024,14,Jalisco,Rapto,Rapto,agosto,0,dato vacío,8,20248
166746,2022,29,Tlaxcala,Robo,Robo a casa habitación,junio,17,dato vacío,6,20226
106629,2020,2,Baja California,Otros delitos que atentan contra la libertad p...,Otros delitos que atentan contra la libertad p...,noviembre,42,dato vacío,11,202011
165143,2022,27,Tabasco,Electorales,Electorales,septiembre,0,dato vacío,9,20229
55736,2017,21,Puebla,Lesiones,Lesiones dolosas,mayo,174,dato vacío,5,20175

In [29]:
# Agregamos la columna de fecha juntando el año y el mes
datos_long['fecha'] = pd.to_datetime(datos_long['anio'].astype(str) + datos_long['mes'].astype(str), format='%Y%m')
datos_long.sample(5)

,anio,clave_ent,entidad,tipo_de_delito,subtipo_de_delito,nombre_mes,frecuencia,nueva_columna,mes,anio_mes,fecha
91970,2019,12,Guerrero,Homicidio,Homicidio doloso,diciembre,139,dato vacío,12,201912,2019-12-01
9023,2015,14,Jalisco,Robo,Robo a institución bancaria,septiembre,5,dato vacío,9,20159,2015-09-01
45480,2017,5,Coahuila de Zaragoza,Tráfico de menores,Tráfico de menores,abril,0,dato vacío,4,20174,2017-04-01
38446,2016,27,Tabasco,Extorsión,Extorsión,octubre,15,dato vacío,10,201610,2016-10-01
155070,2022,11,Guanajuato,Violación simple,Violación simple,junio,70,dato vacío,6,20226,2022-06-01

In [30]:
# Eliminamos las columnas que ya no necesitamos
datos_long = datos_long.drop(columns=['nueva_columna'])
datos_long.sample(5)

,anio,clave_ent,entidad,tipo_de_delito,subtipo_de_delito,nombre_mes,frecuencia,mes,anio_mes,fecha
73316,2018,16,Michoacán de Ocampo,Allanamiento de morada,Allanamiento de morada,mayo,21,5,20185,2018-05-01
6820,2015,11,Guanajuato,Homicidio,Homicidio culposo,febrero,103,2,20152,2015-02-01
84280,2018,32,Zacatecas,Robo,Robo a transeúnte en espacio abierto al público,febrero,0,2,20182,2018-02-01
231299,2025,31,Yucatán,Lesiones,Lesiones dolosas,septiembre,27,9,20259,2025-09-01
99415,2019,23,Quintana Roo,Robo,Otros robos,marzo,291,3,20193,2019-03-01

In [31]:
datos_long[
    (datos_long.tipo_de_delito == "Homicidio") &
    (datos_long.clave_ent == 20) &
    (datos_long.fecha >= '2024-01-01')
].sort_values('fecha')

,anio,clave_ent,entidad,tipo_de_delito,subtipo_de_delito,nombre_mes,frecuencia,mes,anio_mes,fecha
202839,2024,20,Oaxaca,Homicidio,Homicidio culposo,enero,87,1,20241,2024-01-01
202851,2024,20,Oaxaca,Homicidio,Homicidio doloso,enero,67,1,20241,2024-01-01
202840,2024,20,Oaxaca,Homicidio,Homicidio culposo,febrero,106,2,20242,2024-02-01
202852,2024,20,Oaxaca,Homicidio,Homicidio doloso,febrero,60,2,20242,2024-02-01
202843,2024,20,Oaxaca,Homicidio,Homicidio culposo,marzo,122,3,20243,2024-03-01
202855,2024,20,Oaxaca,Homicidio,Homicidio doloso,marzo,62,3,20243,2024-03-01
202836,2024,20,Oaxaca,Homicidio,Homicidio culposo,abril,127,4,20244,2024-04-01
202848,2024,20,Oaxaca,Homicidio,Homicidio doloso,abril,73,4,20244,2024-04-01
202856,2024,20,Oaxaca,Homicidio,Homicidio doloso,mayo,73,5,20245,2024-05-01
202844,2024,20,Oaxaca,Homicidio,Homicidio culposo,mayo,150,5,20245,2024-05-01
202842,2024,20,Oaxaca,Homicidio,Homicidio culposo,junio,123,6,20246,2024-06-01
202854,2024,20,Oaxaca,Homicidio,Homicidio doloso,junio,72,6,20246,2024-06-01
202841,2024,20,Oaxaca,Homicidio,Homicidio culposo,julio,126,7,20247,2024-07-01
202853,2024,20,Oaxaca,Homicidio,Homicidio doloso,julio,75,7,20247,2024-07-01
202837,2024,20,Oaxaca,Homicidio,Homicidio culposo,agosto,102,8,20248,2024-08-01
202849,2024,20,Oaxaca,Homicidio,Homicidio doloso,agosto,84,8,20248,2024-08-01
202859,2024,20,Oaxaca,Homicidio,Homicidio doloso,septiembre,87,9,20249,2024-09-01
202847,2024,20,Oaxaca,Homicidio,Homicidio culposo,septiembre,103,9,20249,2024-09-01
202846,2024,20,Oaxaca,Homicidio,Homicidio culposo,octubre,98,10,202410,2024-10-01
202858,2024,20,Oaxaca,Homicidio,Homicidio doloso,octubre,87,10,202410,2024-10-01
202845,2024,20,Oaxaca,Homicidio,Homicidio culposo,noviembre,94,11,202411,2024-11-01
202857,2024,20,Oaxaca,Homicidio,Homicidio doloso,noviembre,74,11,202411,2024-11-01
202838,2024,20,Oaxaca,Homicidio,Homicidio culposo,diciembre,88,12,202412,2024-12-01
202850,2024,20,Oaxaca,Homicidio,Homicidio doloso,diciembre,63,12,202412,2024-12-01
223959,2025,20,Oaxaca,Homicidio,Homicidio culposo,enero,102,1,20251,2025-01-01
223971,2025,20,Oaxaca,Homicidio,Homicidio doloso,enero,68,1,20251,2025-01-01
223972,2025,20,Oaxaca,Homicidio,Homicidio doloso,febrero,43,2,20252,2025-02-01
223960,2025,20,Oaxaca,Homicidio,Homicidio culposo,febrero,98,2,20252,2025-02-01
223975,2025,20,Oaxaca,Homicidio,Homicidio doloso,marzo,64,3,20253,2025-03-01
223963,2025,20,Oaxaca,Homicidio,Homicidio culposo,marzo,129,3,20253,2025-03-01
223956,2025,20,Oaxaca,Homicidio,Homicidio culposo,abril,124,4,20254,2025-04-01
223968,2025,20,Oaxaca,Homicidio,Homicidio doloso,abril,61,4,20254,2025-04-01
223976,2025,20,Oaxaca,Homicidio,Homicidio doloso,mayo,65,5,20255,2025-05-01
223964,2025,20,Oaxaca,Homicidio,Homicidio culposo,mayo,107,5,20255,2025-05-01
223962,2025,20,Oaxaca,Homicidio,Homicidio culposo,junio,86,6,20256,2025-06-01
223974,2025,20,Oaxaca,Homicidio,Homicidio doloso,junio,46,6,20256,2025-06-01
223961,2025,20,Oaxaca,Homicidio,Homicidio culposo,julio,88,7,20257,2025-07-01
223973,2025,20,Oaxaca,Homicidio,Homicidio doloso,julio,71,7,20257,2025-07-01
223969,2025,20,Oaxaca,Homicidio,Homicidio doloso,agosto,79,8,20258,2025-08-01
223957,2025,20,Oaxaca,Homicidio,Homicidio culposo,agosto,27,8,20258,2025-08-01
223967,2025,20,Oaxaca,Homicidio,Homicidio culposo,septiembre,18,9,20259,2025-09-01
223979,2025,20,Oaxaca,Homicidio,Homicidio doloso,septiembre,78,9,20259,2025-09-01
223966,2025,20,Oaxaca,Homicidio,Homicidio culposo,octubre,20,10,202510,2025-10-01
223978,2025,20,Oaxaca,Homicidio,Homicidio doloso,octubre,65,10,202510,2025-10-01
223977,2025,20,Oaxaca,Homicidio,Homicidio doloso,noviembre,68,11,202511,2025-11-01
223965,2025,20,Oaxaca,Homicidio,Homicidio culposo,noviembre,20,11,202511,2025-11-01
223970,2025,20,Oaxaca,Homicidio,Homicidio doloso,diciembre,73,12,202512,2025-12-01
223958,2025,20,Oaxaca,Homicidio,Homicidio culposo,diciembre,18,12,202512,2025-12-01

In [32]:
#Le damos un nombre a nuestra nueva estructura de datos y verificamos que incluye la información que vamos a necesitar:
datos_finales2 = datos_long[['anio', 'clave_ent', 'entidad', 'tipo_de_delito', 'subtipo_de_delito', 'nombre_mes', 'fecha', 'frecuencia']]
datos_finales2.head(2)

,anio,clave_ent,entidad,tipo_de_delito,subtipo_de_delito,nombre_mes,fecha,frecuencia
0,2015,1,Aguascalientes,Aborto,Aborto,abril,2015-04-01,0
1,2015,1,Aguascalientes,Aborto,Aborto,agosto,2015-08-01,0

In [33]:
datos_finales2.to_csv('delitos2.csv', index=False)